title = "Simplex"
enableRobotsTXT = true
defaultContentLanguage = "pt"

themesdir = "themes"
theme = "rusty-typewriter"

[params]
dateFormat = "2006-01-02"

[params.author]
name = "Simplex"

[markup.highlight]
style = "github-dark"

[taxonomies]
palavra-chave = "palavras-chave"
categoria = "categoria"
rubrica = "rubrica"
ano = "ano"

[related]
includeNewer = true
[[related.indices]]
name = "palavras-chave"
weight = 80
[[related.indices]]
name = "rubrica"
weight = 20

[params.rtwt]
searchPath = "pesquisa"
countPageItems = "15"

[params.rtwt.side.home]
sidePaneSticky = false
taxonomies = ["palavras-chave", "rubrica", "ano"]
countTaxonomy = 5

[params.rtwt.side.single]
sidePaneSticky = true
showDetails = true
showTableOfContents = true
showAttachments = true
showRelated = true
countRelated = 3

[languages.pt]
locale = "pt-BR"
label = "Português"

[languages.pt.pagination]
disableAliases = false
path = 'pagina'

[[languages.pt.menus.main]]
name = "Séries"
pageRef = "/series"
weight = 1

[[languages.pt.menus.main]]
name = "Arquivo"
pageRef = "/artigos"
weight = 2

[[languages.pt.menus.main]]
name = "Pesquisa"
url = "/pesquisa"
weight = 3

[[languages.pt.menus.main]]
name = "Sobre"
url = "/sobre"
weight = 4

[[languages.pt.menus.main]]
name = "RSS"
url = "/index.xml"
weight = 5

[caches.images]
dir = ":cacheDir/images"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[mediaTypes."application/json"]
suffixes = ["json"]

[outputs]
home = ["html", "rss", "SearchIndex"]
section = ['html', 'rss']
taxonomy = ['html']
term = ['html']

[services.rss]
limit = 16
